/* eslint-disable camelcase */
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../styles/globals.css'
import { UserContextProvider } from '@/contexts/user-context'
import { Header } from '@/components/header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <UserContextProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased text-white`}
        >
          <Header />
          <div className="pt-20 px-5 bg-gray-900 h-screen flex">{children}</div>
        </body>
      </UserContextProvider>
    </html>
  )
}
